# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 08:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oidc_rp_client_id', models.CharField(max_length=255)),
                ('oidc_rp_client_secret', models.CharField(max_length=255)),
                ('oidc_rp_scopes', models.CharField(blank=True, default='openid profile email address phone site roles', max_length=255)),
                ('extra_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('wagtail_redirect_url', models.URLField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
